print('Importing DCGAN Class')
from dust_gan import DustDCGAN
print('Instantiate GAN')
dust_gan = DustDCGAN('/global/homes/k/kmaylor/cori/Maps_and_Makers/Planck_dust_cuts_353GHz.pk',load_state=False)
print('Begin Training')
dust_gan.train(train_steps=4000, batch_size=32, save_interval=100)
print('Saving GAN')
dust_gan.DCGAN.save_dcgan()
#dust_gan.plot_images(fake=True)
#dust_gan.plot_images(fake=False, save2file=True)
